name: maidterm_app
description: MaidTerm - a local-first desktop terminal for macOS, Windows and Linux.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  file_picker: ^11.0.3
  flutter_pty:
    path: packages/flutter_pty
  flutter_local_notifications: ^22.3.0
  island_ui_foundation:
    git:
      url: https://src.solsynth.dev/SoSYS/Solian.git
      path: packages/island_ui_foundation
      ref: a936275e6e0e43de3eddbc0ed812308742e2b017
  material_ui: ^1.0.1
  flutter_localizations:
    sdk: flutter
  maidterm:
    path: packages/maidterm
  window_manager:
    git:
      url: https://github.com/boyan01/window_manager.git
      path: packages/window_manager
      ref: 6fae92d21b4c80ce1b8f71c1190d7970cf722bd4
  solsynth_express:
    git:
      url: https://src.solsynth.dev/SoSYS/Solian.git
      path: packages/solsynth_express
      ref: a936275e6e0e43de3eddbc0ed812308742e2b017
  hooks_riverpod: ^3.4.2
  shared_preferences: ^2.5.5
  uuid: ^4.6.0
  collection: ^1.19.1
  material_symbols_icons: ^4.2960.0
  package_info_plus: ^9.0.1
  path_provider: ^2.1.6
  system_fonts: ^1.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  #image_path_ios_dark_transparent: "assets/icons/icon-dark.png"
  remove_alpha_ios: true
  desaturate_tinted_to_grayscale_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#f2a39d"
    theme_color: "#f2a39d"
  windows:
    generate: true
    image_path: "assets/icons/icon-padded.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icons/icon-padded.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/sans/IBMPlexSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/sans/IBMPlexSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/mono/IBMPlexMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/mono/IBMPlexMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/mono/IBMPlexMono-Light.ttf
          weight: 300
        - asset: assets/fonts/mono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/mono/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/mono/IBMPlexMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mono/IBMPlexMono-Bold.ttf
          weight: 700
